language: java

git:
  quiet: false
    
before_install:
- gradle installWrapper
    
jobs:
  allow_failures:
  - os: osx
  include:
    - jdk: openjdk11
      os: linux
    - jdk: openjdk11
      os: osx
     
notifications:
  email:
    recipients:
    - s4alurba@uni-trier.de
  on_success: never
  on_failure: always
    
script: ./gradlew buildCore
